// Last-line output filter for anything generated by the model before it reaches
// the client. This is NOT sufficient on its own: a determined attacker can
// paraphrase or transliterate a secret around a pattern match. The job here is
// to catch the obvious shapes — a key the model was somehow coaxed into echoing
// — so a single failure in the layers above (system prompt, input caps) does
// not cash out into a leaked credential. The real defense is the layers that
// keep the model from forming the output in the first place; this is the net
// under them.

const PATTERNS: RegExp[] = [
  // Anthropic API keys.
  /sk-ant-[A-Za-z0-9_-]{10,}/g,
  // Stripe secret/restricted/publishable keys and webhook signing secrets.
  /(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]{10,}/g,
  /whsec_[A-Za-z0-9]{10,}/g,
  // Generic OpenAI-style secret keys.
  /sk-[A-Za-z0-9]{20,}/g,
  // JSON Web Tokens (header.payload.signature).
  /eyJ[A-Za-z0-9_-]{6,}\.eyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}/g,
  // Database connection URLs that carry an inline password.
  /\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis):\/\/[^\s:@/]+:[^\s@/]+@[^\s]+/gi,
];

// Environment-variable-shaped disclosures: a NAME that looks like a secret
// (contains SECRET / API_KEY / TOKEN / PASSWORD / PRIVATE_KEY) assigned a value.
// We redact the value, not the name, so the message stays legible.
const ENV_ASSIGN =
  /\b([A-Z][A-Z0-9_]*(?:SECRET|API_KEY|TOKEN|PASSWORD|PRIVATE_KEY)[A-Z0-9_]*)\s*([:=])\s*("?)([^\s"]+)\3/g;

/**
 * Replace anything that looks like a credential with [REDACTED].
 * Imperfect by design; see the note at the top of the file.
 */
export function redactSecrets(text: string): string {
  let out = text;
  for (const pattern of PATTERNS) {
    out = out.replace(pattern, '[REDACTED]');
  }
  out = out.replace(ENV_ASSIGN, (_m, name, sep) => `${name}${sep} [REDACTED]`);
  return out;
}
